// This pipeline specifically will build a .NET CORE Spplication

pipeline {

    triggers {
        pollSCM('H/5 * * * *')
    }	 

    // The context (container) in which to run the stages
    agent any 

    stages {

        // Gets the Application Code 
         stage ('Get Latest Code') {
                // git url: 'https://github.com/adriancofie/aspdotnet_app.git'
         git branch: 'master', url: 'https://github.com/adriancofie/aspdotnet_app.git'
        }


        // Build the Docker image based on the Dockerfile within the checked out code. 
        stage("Docker build"){
                    steps {	
                        sh "docker build -t reponame/myApplication:latest ."
                    }
                }	

        // Run the Docker Image and ites  releveant build process is specified in its 
        stage('Restore Packages') {
            steps {
                bat "dotnet restore"  
            }
        }

        stage ('Clean') {
            steps {
                bat "dotnet clean"
                }    
            }
        }

        stage('Build') {
            steps {
                bat "dotnet build -c Release -o out"
            }
        
    
        // stage ('Publish Binaries') {
        //     steps {	
        //         sh ""
        //     }
        // }

        }// End Stages


        post {
            always {            
                cleanWs()
            }
        }   
}//End Pipeline

